# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5344bc69a47214491d07bf809e412de84062a953d1f66c88113d68961460c5e919317498831a3a37f305131024e8d943a84368fdaeb19573fd1f24387d0f318

test:
  secret_key_base: 4fbd7f4ff9bb4b9e4f2fb136c4dda687c5dde291445cf01ffd169e36ce0477bedc8a2a338bf2c490c59b3a81b33e072c83228f86efff7856e7873ced804cee14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
